server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 30m

spring:
  application:
    name: lighten
  profiles:
    active: ${lighten:dev}
  thymeleaf:
    prefix: classpath:/view/

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 500MB






