spring:
  datasource:
    url: jdbc:h2:file:./data/db/${spring.application.name}
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2
      enabled: true
